apiVersion: v1
kind: Pod
metadata:
     name: qapod2
     labels:
        env: qa
        business: hr
        tier: backend
        technology: java
spec:
     containers:
     - name: pythonwebpage
       image: deepcloud2208/k8s-eks-gke:latest
       env:
       - name: NAME
         value: "python container inside a pod"
     - name: httpwebpage
       image: deepcloud2208/httpwebpagecontainer:latest