apiVersion: v1
kind: Pod
metadata:
     name: prodpod1
     labels:
        env: prod
        business: finance
        tier: backend
        technology: python
spec:
     containers:
     - name: pythonwebpage
       image: deepcloud2208/k8s-eks-gke:latest
       env:
       - name: NAME
         value: "python container inside a pod"
     - name: httpwebpage
       image: deepcloud2208/httpwebpagecontainer:latest