apiVersion: v1
kind: Pod
metadata:
     name: devpod
     labels:
        env: dev
        business: payroll
        tier: frontend
        technology: angular
spec:
     containers:
     - name: pythonwebpage
       image: deepcloud2208/k8s-eks-gke:latest
       env:
       - name: NAME
         value: "python container inside a pod"
     - name: httpwebpage
       image: deepcloud2208/httpwebpagecontainer:latest