apiVersion: v1
kind: Pod
metadata:
     name: standalonepod1
     labels:
        purpose: training
        topic: k8sreplicaset
        subtopic: nontemplatedpod
spec:
     containers:
     - name: httpwebpage
       image: deepcloud2208/httpwebpagecontainer:latest