apiVersion: v1
kind: Service
metadata:
    name: k8s-external-service
    labels:
        env: training
        chapter: service
        topic: external-service
spec:
    ports:
    - targetPort: 3306
      port: 9000
      protocol: TCP