apiVersion: apps/v1
kind: Deployment
metadata:
      name: deployment-with-replicas
      labels:
         env: deploymenttraining2
spec:
   replicas: 3
   selector:
      matchLabels:
         topic: deploymentpods2
   template:
      metadata:
         name: standalonepod
         labels:
            topic: deploymentpods2
      spec:
         containers:
         - name: httpwebpage
           image: deepcloud2208/httpwebpagecontainer:latest