apiVersion: v1
kind: Service
metadata:
	name: k8s-service-nodeport
	labels: 
		env: training
		app: http-app
spec:
	type: NodePort
 	ports:
   	- targetPort: 80
 	  port: 8080
   	  nodePort: 32500
    selector:
      env: training
      chapter: services
      section: seven
