apiVersion: v1
kind: Service
metadata:
  name: k8s-service-clusterip
  labels:
     env: training
     app: http-app
spec:
  type: ClusterIP
  ports:
  - targetPort: 80
    port: 8082
  selector:
    env: training
    chapter: services
    section: seven