apiVersion: v1
kind: Pod
metadata:
     name: k8spodsintro1
     labels:
        env: training
        chapter: pods
spec:
     containers:
     - name: pythonwebpage
       image: deepcloud2208/k8s-eks-gke:latest
       env:
       - name: NAME
         value: "python container inside a pod"
     - name: httpwebpage
       image: deepcloud2208/httpwebpagecontainer:latest