apiVersion: v1
kind: Pod
metadata:
     name: k8spodsintro2
     labels: 
        env: training
        chapter: pods
spec:
     containers:
     - name: httpwebpage
       image: deepcloud2208/httpwebpagecontainer:latest
